export const siteConfig = {
  name: "Virelio",
  description: "AI-agents die samenwerken, delegeren en uitvoeren — live in 2 weken. Gevestigd in Amsterdam.",
  url: "https://virelio.nl",
  metadataBase: "https://virelio.nl",
  logoUrl: "/logo.svg",
  ogImage: "/og-image.png",
  twitterHandle: "@Virelio",
  locale: "nl",
  authors: [
    {
      name: "Virelio Team",
      url: "https://virelio.nl",
    },
  ],
  socials: {
    twitter: "https://twitter.com/Virelio",
    github: "https://github.com/Virelio",
    linkedin: "https://linkedin.com/company/Virelio",
  },
  contact: {
    email: "info@virelio.nl",
    phone: "+31687838713",
    address: "Amsterdam, Netherlands",
  },
  themeColor: "#ffffff",
  keywords: [
    "AI agents op maat",
    "custom AI agents",
    "AI agent bouwen",
    "AI automatisering bedrijven",
    "digitale medewerkers",
    "AI bureau Amsterdam",
    "klantenservice automatiseren",
    "sales automatisering",
    "RAG development",
    "retrieval augmented generation",
    "LLM integratie",
    "AI chatbot bouwen",
    "WhatsApp bot bedrijf",
    "kennisbank AI",
    "facturatie automatiseren",
    "on-premise AI",
    "AI oplossingen MKB",
    "bedrijfsprocessen automatiseren",
    "AI integratie bestaande systemen",
    "contract review AI",
    "AI spraakassistent zakelijk",
    "lead kwalificatie AI",
    "AI agent development company",
    "Virelio",
    "Amsterdam",
    "Nederland",
  ],
  // For language-specific URLs (better for SEO)
  alternateLanguages: {
    nl: "https://virelio.nl",
    en: "https://virelio.nl/en",
  },
  // Add sections for the one-page layout
  sections: {
    projects: "#projects",
    services: "#services",
    workshop: "#workshop",
    about: "#about",
    testimonials: "#testimonials",
    demo: "#demo",
    bookMeeting: "#book-meeting",
    contact: "#contact",
    home: "#",
  },
};
